- name: Copy docker builder namespace yaml
  copy: src=docker-builder-namespace.yaml dest=/tmp/docker-builder-namespace.yaml
 
- name: Create docker builder namespace
  command: kubectl apply -f /tmp/docker-builder-namespace.yaml

- name: Copy docker builder service template
  copy: src=docker-builder.yaml dest=/tmp/docker-builder.yaml
 
- name: Create docker builder Service
  command: kubectl apply -f /tmp/docker-builder.yaml