---
- name: Create values file
  template:
    src: values.j2
    dest: /tmp/oscar-values.yaml

- name: Add GRyCAP helm repo
  command: helm repo add grycap https://grycap.github.io/helm-charts/

- name: "Update helm repositories"
  command: helm repo update

# TODO: manage the oscar-svc namespace if openfaas is enabled as ServerlessBackend

- name: Install (or upgrade) the chart
  command: helm upgrade oscar --install grycap/oscar --namespace oscar --create-namespace --values /tmp/oscar-values.yaml
