---
- name: Check if the certs are previously created
  stat:
    path: /opt/nginx-certs/tls.crt
  register: nginx_certs

- name: Certs stuff
  block:
  - name: Create certs directory
    file:
      path: "/opt/nginx-certs"
      state: directory
  - name: Create key and cert
    command: openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=nginxsvc/O=nginxsvc"
    args:
        chdir: "/opt/nginx-certs"
  - name: Create secret with
    command: kubectl create secret tls nginx-tls-secret --key /opt/nginx-certs/tls.key --cert /opt/nginx-certs/tls.crt -n oscar
  when: not nginx_certs.stat.exists

- name: Create deployment and service
  block:
    - template: src=nginx.j2 dest=/tmp/nginx.yml
    - command: kubectl apply -f /tmp/nginx.yml

