- name: Copy OSCAR namespace yaml
  copy: src=oscar-namespace.yaml dest=/tmp/oscar-namespace.yaml
 
- name: Create OSCAR namespace
  command: kubectl apply -f /tmp/oscar-namespace.yaml

- name: Copy OSCAR RBAC yaml
  copy: src=oscar-rbac.yaml dest=/tmp/oscar-rbac.yaml
 
- name: Create OSCAR RBAC
  command: kubectl apply -f /tmp/oscar-rbac.yaml

- name: Copy OSCAR PVC yaml
  template: src=oscar-pvc.j2 dest=/tmp/oscar-pvc.yaml
 
- name: Create OSCAR PVC
  command: kubectl apply -f /tmp/oscar-pvc.yaml
 
- name: Copy OSCAR deployment and service template
  template: src=oscar.j2 dest=/tmp/oscar.yaml
 
- name: Create OSCAR deployment and service
  command: kubectl apply -f /tmp/oscar.yaml 