- name: Copy OSCAR namespace yaml
  copy: src=oscar-namespace.yaml dest=/tmp/oscar-namespace.yaml
 
- name: Create OSCAR namespace
  command: kubectl apply -f /tmp/oscar-namespace.yaml
 
- name: Copy OSCAR service template
  template: src=oscar.j2 dest=/tmp/oscar.yaml
 
- name: Create OSCAR Service
  command: kubectl apply -f /tmp/oscar.yaml 