---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oscar-controller
  namespace: oscar
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: oscar-controller
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: oscar-controller-global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oscar-controller
subjects:
- kind: ServiceAccount
  name: oscar-controller
  namespace: oscar