---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oscar-sa
  namespace: oscar
---
# ClusterRole and ClusterRoleBinding to create Kaniko builds as jo
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oscar-kaniko-controller
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oscar-kaniko-controller-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oscar-kaniko-controller
subjects:
- kind: ServiceAccount
  name: oscar-sa
  namespace: oscar
---
# Role and RoleBinding to create and delete OneTrigger deployments
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oscar-onetrigger-controller
  namespace: oscar
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oscar-onetrigger-controller-binding
  namespace: oscar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oscar-onetrigger-controller
subjects:
- kind: ServiceAccount
  name: oscar-sa
  namespace: oscar